package p1;

import java.util.Scanner;

public class Main {

	public static void main(String[] args) {
		System.out.println("***********Number Game***********");
		try (Scanner s = new Scanner(System.in)) {
			Integer n = (int) (Math.random() * 49 + 1);
			System.out.println("A Random Number between 1 to 50 is generated by system You have to guess it.");
			for (int i = 1; i <= 10; i++) {

				System.out.println("Guess the Number which is from 1-50");
				Integer x = s.nextInt();
				if (x > 0 && x <= 50) {
					if (n.equals(x)) {
						System.out.println("You Won!" + "\n");
						System.out.println("\t1.Enter 1 to Play again\n\t2.Enter 2 to Exit");
						switch (s.nextInt()) {
						case 1:
							continue;
						case 2:
							System.out.println("Game Over");
							System.exit(0);
						default:
							System.out.println("Invalid Choice!");
						}
					} else {
						if (n > x) {
							System.out.println("Too low");

						} else {
							System.out.println("Too high");

						}

					}
					if (i == 10) {
						System.out.println("Sorry! you're tryed wrongly many times, Play new Game.");
						break;
					}
				} else {
					System.out.println("Please Enter Number between 1 to 50 only.");
				}
			}
		}
	}
}
